<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>apSettings Documentation</title>
    <!-- Tailwind CSS CDN -->
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
  </head>

  <body class="bg-gray-100 bg-gradient-to-b from-blue-200 to-white pb-48">
      <div class="w-10/12 mx-auto p-4">
        <h1 class="text-5xl font-bold mb-6 py-10 text-blue-900">
          AutoProctor Documentation
        </h1>
      <ul id="init-params" class="w-11/12 border-b-2 list-disc list-inside pb-6">

        <h2 class="text-3xl font-bold mb-4 text-green-700">
          1. initAutoProctor Parameters
        </h2>
        <p class="mb-4">
          The following parameters are used when initializing AutoProctor:
        </p>

        <li class="my-3 leading-2">
          <strong>testAttemptId:</strong> AutoProctor identifies each test
          attempt by a testAttemptId, which is a unique ID generated by your own
          platform. The testAttemptId can have a maximum length of 15
          characters.
        </li>
        <li class="my-3 leading-2">
          <strong>tenantId:</strong> A unique ID that identifies you as a tenant
          on AutoProctor. You will receive your tenantId and client_secret when
          you sign up on AutoProctor as a tenant.
        </li>
        <li class="my-3 leading-2">
          <strong>hashedTestAttemptId:</strong> AutoProctor uses HMAC with
          SHA256 for authentication. The hashedTestAttemptId is generated using
          the testAttemptId and tenantId, along with your client_secret as the
          HMAC key. This ensures that you are authorized to perform actions
          allowed by the AutoProctor SDK. Passing an invalid hashedTestAttemptId
          will result in a 403 Forbidden error from AutoProctor.
        </li>
      </ul>

      <table id="ap-settings" class="w-11/12 bg-white border border-gray-200 shadow-md rounded">
        <h2 class="text-3xl font-bold mb-4 text-green-700 mt-24">2. apSettings</h2>
        <p class="mb-4">
          The apSettings parameter contains the configuration options for
          AutoProctor.
        </p>
        <thead class="bg-gray-100">
          <tr>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left w-1/5"
            >
              Parameter
            </th>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left w-1/5"
            >
              Type
            </th>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left w-2/5"
            >
              Description
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">tenantId</td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">String</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The client ID or unique identifier for the tenant.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              testAttemptId
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">String</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The ID associated with the test attempt.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              hashedTestAttemptId
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">String</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The hashed version of the test attempt ID.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.audio
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Indicates whether audio tracking is enabled (true) or disabled
              (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.numHumans
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether the number of humans in the test environment
              should be tracked (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.tabSwitch
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Determines whether tab switching activity should be tracked (true)
              or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.captureSwitchedTab
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Indicates whether capturing of screenshots for switched tabs
              should be enabled (true) or disabled (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.photosAtRandom
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether capturing photos at random intervals should be
              enabled (true) or disabled (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.numPhotosAtRandom
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Number</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The number of photos to capture at random intervals during the
              test. This parameter is only applicable if photosAtRandom is set
              to true.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.preventMultipleScreens
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Determines whether multiple screens (monitor or display) are
              prevented during the test (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.testTakerPhoto
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether capturing a photo of the test taker should be
              enabled (true) or disabled (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.forceCaptureSwitchedTab
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Indicates whether capturing screenshots for switched tabs should
              be forced (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.forcePreventMultipleScreens
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Determines whether preventing multiple screens should be enforced
              (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.forceFullScreen
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether the test environment should be forced into
              full-screen mode (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.previewVideo
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Determines whether video preview should be displayed (true) or not
              (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.forceDesktop
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Indicates whether the test should be forced to run on the desktop
              environment (true) or not (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.showCamPreview
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether the webcam preview should be shown (true) or
              hidden (false).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              trackingOptions.auxiliaryDevice
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Indicates whether an auxiliary device is present (true) or not
              (false). The value of this parameter is determined by the
              condition: &lt;?php echo $test_id; ?&gt; == 1 ? true : false.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              restrictConsole
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Determines whether the console should be restricted (true) or not
              (false). When enabled, access to the browser console may be
              limited or disabled.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              evidencePushInterval
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Number</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The interval in seconds at which evidence is pushed or transmitted
              to the server.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              auxiliaryDeviceRandomPhotoPushInterval
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Number</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The interval in seconds at which random photos captured by the
              auxiliary device are pushed or transmitted to the server.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              userDetails
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Object</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Additional user details associated with the test.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              testDuration
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Number</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The duration of the test in minutes.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">domain</td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">String</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              The domain associated with the platform.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">
              showHowToVideo
            </td>
            <td class="py-2 px-4 border-b border-gray-200 w-1/5">Boolean</td>
            <td class="py-2 px-4 border-b border-gray-200 w-2/5">
              Specifies whether the how-to video should be displayed (true) or
              not (false).
            </td>
          </tr>
        </tbody>
      </table>

      <table
        id="event-codes" class="w-11/12 bg-white border border-gray-200 shadow-md rounded"
      >
        <h2 class="text-3xl font-bold mb-4 text-green-700 mt-24">3. Event Codes</h2>
        <p class="mb-4">
          The following event codes can be used with AutoProctor:
        </p>
        <thead class="bg-gray-100">
          <tr>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left"
            >
              Code
            </th>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left"
            >
              Violation?
            </th>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left"
            >
              Event Type
            </th>
            <th
              class="py-2 px-4 border-b border-gray-200 font-semibold text-left"
            >
              Explanation
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">2001</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorStatusEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Browser is compatible. User has granted permissions.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">2003</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorStatusEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Video and ML model loaded. Ready to start face detection.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4001</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Incompatible Browser. Doesn't pass checkBrowserCompatibility().
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4002</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              From permissions API, user has already blocked access to camera.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4003</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              From permissions API, user has already blocked access to
              microphone.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4004</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              User has proactively declined access to camera/microphone. Or, the
              page is being loaded within an insecure context.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4005</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Hardware error, insecure context, or some other error.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4006</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              From permissions API, user has already blocked access to camera
              and mic.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4007</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Audio Not Readable Error in getUserMedia.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4008</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Video Not Readable Error in getUserMedia.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4009</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              We weren't able to find a microphone on your device. You need to
              enable your microphone, or use another device that has a
              microphone to take this test.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4010</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              We weren't able to find a camera (or webcam) on your device. You
              need to enable your camera, or use another device that has a
              camera to take this test.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4011</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Permission to access a screen area was denied by the user, or the
              current browsing instance is not permitted access to screen
              sharing. Please reload the page to provide the access.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4012</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              The user selected a screen, window, tab, or other source of screen
              data, but a hardware or operating system level error or lockout
              occurred, preventing the sharing of the selected source.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4013</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              No sources of screen video are available for capture.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4014</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              You must share your entire screen in order to proceed with the
              test. Please reload the page to select again.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4015</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              We have detected multiple monitors. Please disconnect the extra
              monitor (or displays like Chromecast). If you continue without
              disconnecting, your teacher will be informed of multiple monitors.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4016</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Use the latest version of Safari on iPhone or iPad. Else, use
              Chrome.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">4017</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorErrorEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Please use Chrome or Firefox if you want to proceed with the test
              (if forceCaptureSwitchedTab is true).
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5001</td>
            <td class="py-2 px-4 border-b border-gray-200">Yes</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              No one looking at the camera.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5002</td>
            <td class="py-2 px-4 border-b border-gray-200">Yes</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              More than 1 Person in Video.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5003</td>
            <td class="py-2 px-4 border-b border-gray-200">No</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Random photo taken.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5004</td>
            <td class="py-2 px-4 border-b border-gray-200">Yes</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Audio above background levels.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5005</td>
            <td class="py-2 px-4 border-b border-gray-200">Yes</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              User switched away from current tab to another tab or application.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5006</td>
            <td class="py-2 px-4 border-b border-gray-200">No</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              User returned to test tab from another tab or application.
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b border-gray-200">5007</td>
            <td class="py-2 px-4 border-b border-gray-200">-</td>
            <td class="py-2 px-4 border-b border-gray-200">
              autoproctorEvidenceEvent
            </td>
            <td class="py-2 px-4 border-b border-gray-200">
              Multiple Monitors detected.
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>
